(bind-key "C-h"     'delete-backward-char)
(bind-key "C-?"     'help-command)
(bind-key "C-c l"   'toggle-truncate-lines)
(bind-key "C-c C-v" 'browse-url-of-buffer)
(bind-key "C-c C-r" 'eval-buffer)
(bind-key "C-c C-g" 'vc-git-grep)
(bind-key "C-c C-k" 'kill-buffer-and-window)
