(global-set-key (kbd "C-h")        'delete-backward-char)
(global-set-key (kbd "M-h")        'backward-kill-word)
(global-set-key (kbd "C-?")        'help-command)
(global-set-key (kbd "C-c l")      'toggle-truncate-lines)
(global-set-key (kbd "C-c C-v")    'browse-url-of-buffer)
(global-set-key (kbd "C-c <up>")   'text-scale-increase)
(global-set-key (kbd "C-c <down>") 'text-scale-decrease)
(global-set-key (kbd "C-c 0")      'text-scale-adjust)
(global-set-key (kbd "C-c C-r")    'eval-buffer)
(global-set-key (kbd "C-c C-g")    'vc-git-grep)
(global-set-key (kbd "C-c C-k")    'kill-buffer-and-window)
