#!/bin/sh
set -eu

[ "$(uname)" != 'Darwin' ] && echo 'brew is unsupported in this platform' && exit

# https://brew.sh
if [ -z "$(command -v brew)" ]; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
brew install \
     bash-completion \
     awscli \
     gibo \
     heroku \
     imagemagick \
     jq \
     mysql \
     node \
     postgresql \
     rbenv \
     redis \
     watch
brew cask install \
     emacs \
     imageoptim \
     sequel-pro \
     virtualbox
brew upgrade
brew cleanup

# setup gibo
GITIGNORE_GLOBAL="${HOME}/.gitignore_global"
gibo macOS Emacs Ruby Rails Node > "$GITIGNORE_GLOBAL"
cat <<EOF >> "$GITIGNORE_GLOBAL"
# Tern.el
.tern-*
EOF
echo "${GITIGNORE_GLOBAL} updated."
