#!/bin/sh
set -eu

# get emacs directory
basedir=$(cd $(dirname $0); pwd)
emacsdir="$(dirname $basedir)/HOME/.emacs.d"

# remove all compiled elisp files
find "$emacsdir" -type f -name '*.elc' | xargs rm -vf

# link emacs directory to home
ln -svf "$emacsdir" "$HOME"

# create environment specific file
config_file="${HOME}/99_env.el"
if [ ! -f "$config_file" ]; then
  cat >"$config_file" <<EOF
;; E.g.
;; (add-to-list 'default-frame-alist '(font . "Ubuntu Mono"))
;; (add-to-list 'default-frame-alist '(top . 0))
;; (add-to-list 'default-frame-alist '(left . 500))
;; (add-to-list 'default-frame-alist '(width . 100))
;; (add-to-list 'default-frame-alist '(height . 35))
EOF
fi

ln -svf "$config_file" "${HOME}/.emacs.d/inits"
