#!/bin/sh
set -eu

# use brew in Mac
[ "$(uname)" = 'Darwin' ] && exit

[ -n "$(command -v heroku)" ] && heroku --version && exit

# https://devcenter.heroku.com/articles/heroku-cli#debian-ubuntu
wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
